title: Site

tabs:
  links:
    label: links
    fields:
      links:
        label: Links
        type: structure 
        fields:
          what: 
            type: text
          where:
            type: text 
          url:
            type: url
          image: 
            type: files
            multiple: false
            help: if an image is added the icon is ignored 
  info:
    label: info
    columns:  
      - width: 3/4
        fields:
          name:
            type: text
            placeholder: So Me One
          handles:
            type: structure
            fields:
              handle:
                type: text
                placeholder: @someone 
              url: 
                type: url
          bio:
            type: writer
      - width: 1/4
        fields:
          avatar:
            label: Avatar
            type: files
            multiple: false 
            size: medium
            layout: cards
            translate: false      
  meta:
    label: meta